name: Basic-CI
on:
  push:
    branches: [ "main" ]   # triggers on every push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a sample test
        run: echo "🚀 CI Pipeline Triggered Successfully by Saurabh!"

